name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set environment variables
        run: |
          echo "VUE_APP_GOOGLE_AP_KEY=${{ secrets.VUE_APP_GOOGLE_AP_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          echo "VUE_APP_GOOGLE_AP_KEY=${{ secrets.VUE_APP_GOOGLE_AP_KEY }}" >> $GITHUB_ENV
          npm run build

      - name: Deploy
        run: |
          npm run deploy
